name: fitness_tracking_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  any_image_view: ^1.0.6
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.1.0
  fl_chart: ^0.68.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  device_preview: ^1.2.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:


  uses-material-design: true


  assets:
    - lib/model/service/localization/language/en.json
    - lib/model/service/localization/language/bn.json
    - assets/app_icon_images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
